<a href="https://colab.research.google.com/github/maskubica/python/blob/master/1_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 1. Numpy

In [1]:
import numpy as np

### Defining vector


In [2]:
np.array([0,1,2,3,4,5,6,7,8,9,10])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.arange(0,10,step=1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [6]:
v = np.array([0,1,2,3,4,5,6,7,8,9,10])
type(v)

numpy.ndarray

In [7]:
np.shape(v)

(11,)

### Defining Matrix


In [8]:
np.arange(0,10,1).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
A = np.arange(0,25).reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
np.diag(A, 2)

array([ 2,  8, 14])

### Broadcasting

In [11]:
v = np.arange(1,10,1)

print(v+v)
print("Difference: %s" % str(v-v))
print("Division:" + str(v/v))
print(f"Multiplication: {v*v}")

[ 2  4  6  8 10 12 14 16 18]
Difference: [0 0 0 0 0 0 0 0 0]
Division:[1. 1. 1. 1. 1. 1. 1. 1. 1.]
Multiplication: [ 1  4  9 16 25 36 49 64 81]


### Linear Algebra


In [19]:
A = np.arange(0,10,1).reshape(2,5)
v = np.arange(0,5,1)
A, v
np.dot(A,A)
A @ A.T

array([[ 30,  80],
       [ 80, 255]])

In [23]:
np.linalg.inv(A @ A.T)

array([[ 0.204, -0.064],
       [-0.064,  0.024]])

In [ ]:
import random
rows=1000
cols=1000
A = np.array(random.sample(list(np.arange(0,rows*cols)),rows*cols)).reshape(rows,cols)
np.linalg.inv(A)

array([32, 28, 94, 85, 42, 57,  5, 53, 71, 82,  7, 65, 97, 39, 54, 13, 48,
       50, 98, 15, 81,  6, 73, 20, 72, 24, 70, 90,  1, 84, 10,  9, 66, 36,
       22, 91,  0, 56, 12, 74, 51, 55, 37, 27, 19, 64, 25, 11, 38, 58, 99,
       95, 17, 18, 34, 86, 75,  3, 88, 77, 47, 52, 41, 33, 40, 16, 62, 26,
       23, 96, 14, 59, 89, 45, 63, 60, 78, 69, 35, 79, 43, 87,  4,  8, 80,
        2, 49, 29, 31, 93, 68, 21, 46, 30, 67, 61, 76, 44, 83, 92])

W have two matrices with dimensions $n \times d$ and $m \times d$. The goal is to create a $n \times m$ matrix with distances between every pair of vectors.

In [1]:
import time
start = time.time()



end = time.time()
print(f"Elapsed time: {end-start}")


Elapsed time: 2.3365020751953125e-05
