<a href="https://colab.research.google.com/github/maskubica/python/blob/master/1_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 1. Numpy

In [ ]:
import numpy as np

### Defining vector


In [ ]:
np.array([0,1,2,3,4,5,6,7,8,9,10])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.arange(0,10,step=1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
v = np.array([0,1,2,3,4,5,6,7,8,9,10])
type(v)

numpy.ndarray

In [ ]:
np.shape(v)

(11,)

### Defining Matrix


In [ ]:
np.arange(0,10,1).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
A = np.arange(0,25).reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
np.diag(A, 2)

array([ 2,  8, 14])

### Broadcasting

In [ ]:
v = np.arange(1,10,1)

print(v+v)
print("Difference: %s" % str(v-v))
print("Division:" + str(v/v))
print(f"Multiplication: {v*v}")

[ 2  4  6  8 10 12 14 16 18]
Difference: [0 0 0 0 0 0 0 0 0]
Division:[1. 1. 1. 1. 1. 1. 1. 1. 1.]
Multiplication: [ 1  4  9 16 25 36 49 64 81]
