<a href="https://colab.research.google.com/github/maskubica/python/blob/master/1_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 1. Numpy

In [5]:
import numpy as np

### Defining vector


In [6]:
np.array([0,1,2,3,4,5,6,7,8,9,10])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.arange(0,10,step=1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [10]:
v = np.array([0,1,2,3,4,5,6,7,8,9,10])
type(v)

numpy.ndarray

In [11]:
np.shape(v)

(11,)

### Defining Matrix


In [12]:
np.arange(0,10,1).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
A = np.arange(0,25).reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
np.diag(A, 2)

array([ 2,  8, 14])

### Broadcasting

In [15]:
v = np.arange(1,10,1)

print(v+v)
print("Difference: %s" % str(v-v))
print("Division:" + str(v/v))
print(f"Multiplication: {v*v}")

[ 2  4  6  8 10 12 14 16 18]
Difference: [0 0 0 0 0 0 0 0 0]
Division:[1. 1. 1. 1. 1. 1. 1. 1. 1.]
Multiplication: [ 1  4  9 16 25 36 49 64 81]


### Linear Algebra


In [20]:
A = np.arange(0,10,1).reshape(2,5)
v = np.arange(0,5,1)
A, v
np.dot(A,v)
#A @ A.T

array([30, 80])

In [ ]:
np.linalg.inv(A @ A.T)

In [ ]:
import random
rows=1000
cols=1000
A = np.array(random.sample(list(np.arange(0,rows*cols)),rows*cols)).reshape(rows,cols)
np.linalg.inv(A)

W have two matrices with dimensions $n \times d$ and $m \times d$. The goal is to create a $n \times m$ matrix with distances between every pair of vectors.

[Tip](https://medium.com/@souravdey/l2-distance-matrix-vectorization-trick-26aa3247ac6c)

In [108]:
n, m = 10000, 5000 
d = 50

A = np.random.rand(n,d)
B = np.random.rand(m,d)

In [ ]:
import time
start = time.time()


res1 = np.zeros((n, m))
for i in range(n):
    for j in range(m):
        res1[i, j] = np.sum((A[i] - B[j])**2)


end = time.time()
print(f"Elapsed time: {end-start}")


In [ ]:
import time
start = time.time()


res2 = np.zeros((n, m))
for i in range(n):
  res2[i, :] = np.sum((B - A[i])**2, axis=1)


end = time.time()
print(f"Elapsed time: {end-start}")

In [ ]:
import time
start = time.time()

res3 = -2 * np.dot(A, B.T) + np.sum(B**2, axis=1) + np.sum(A**2, axis=1)[:, np.newaxis]

end = time.time()
print(f"Elapsed time: {end-start}")


In [ ]:
np.sum(res2-res3)